[project]
name = "teluxmmu-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "dagshub>=0.7.0",
    "matplotlib>=3.10.8",
    "mlflow>=1.27.0",
    "numpy==2.4.3",
    "opencv-python>=4.13.0.92",
    "pandas>=3.0.2",
    "pillow==12.1.1",
    "protobuf<4.0.0",
    "scikit-learn>=1.8.0",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "tqdm>=4.67.3",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu130"

[tool.uv]
index-strategy = "unsafe-best-match"
